Update to show running and unknown statuses

diff --git a/bin/aws-pipeline-status-plain b/bin/aws-pipeline-status-plain
--- a/bin/aws-pipeline-status-plain
+++ b/bin/aws-pipeline-status-plain
@@ -9,7 +9,19 @@ fi
 if [ ! -f /tmp/aws-pipeline-status/numservices ]; then
   echo 0 > /tmp/aws-pipeline-status/numservices
 fi
+if [ ! -f /tmp/aws-pipeline-status/numrunning ]; then
+  echo 0 > /tmp/aws-pipeline-status/numrunning
+fi
+if [ ! -f /tmp/aws-pipeline-status/numunknown ]; then
+  echo 0 > /tmp/aws-pipeline-status/numunknown
+fi
+if [ ! -f /tmp/aws-pipeline-status/numsucceeded ]; then
+  echo 0 > /tmp/aws-pipeline-status/numsucceeded
+fi
+
 numfailing=`cat /tmp/aws-pipeline-status/numfailing || echo 0`
 numservices=`cat /tmp/aws-pipeline-status/numservices || echo 0`
-numnotfailing=`echo "$numservices - $numfailing" | bc`
-echo "$numfailing $numnotfailing $numservices"
+numsucceeded=`cat /tmp/aws-pipeline-status/numsucceeded || echo 0`
+numrunning=`cat /tmp/aws-pipeline-status/numrunning || echo 0`
+numunknown=`cat /tmp/aws-pipeline-status/numunknown || echo 0`
+echo "$numfailing $numsucceeded $numrunning $numunknown"
